-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

USE DATABASE DEV;

-- List all schemas
SHOW SCHEMAS IN DATABASE DEV;

-- List all stages with details
SELECT 
    CATALOG_NAME as DATABASE,
    SCHEMA_NAME,
    STAGE_NAME,
    STAGE_TYPE,
    STAGE_URL,
    COMMENT,
    CREATED,
    LAST_ALTERED
FROM DEV.INFORMATION_SCHEMA.STAGES
WHERE STAGE_TYPE = 'INTERNAL'
ORDER BY SCHEMA_NAME, STAGE_NAME;

-- List all file formats with details
SELECT 
    CATALOG_NAME as DATABASE,
    SCHEMA_NAME,
    FILE_FORMAT_NAME,
    FILE_FORMAT_TYPE,
    RECORD_DELIMITER,
    FIELD_DELIMITER,
    COMPRESSION,
    COMMENT,
    CREATED,
    LAST_ALTERED
FROM DEV.INFORMATION_SCHEMA.FILE_FORMATS
ORDER BY SCHEMA_NAME, FILE_FORMAT_NAME;

-- Check warehouse status
SHOW WAREHOUSES LIKE 'DEV_WH';

-- Check current roles and grants
SHOW ROLES;
SHOW GRANTS TO ROLE DEV_DEVELOPER;
SHOW GRANTS TO ROLE DEV_ANALYST;

-- Summary of database objects
SELECT 
    'Schemas' as OBJECT_TYPE,
    COUNT(*) as COUNT
FROM DEV.INFORMATION_SCHEMA.SCHEMATA
WHERE CATALOG_NAME = 'DEV'
UNION ALL
SELECT 
    'Stages' as OBJECT_TYPE,
    COUNT(*) as COUNT
FROM DEV.INFORMATION_SCHEMA.STAGES
WHERE CATALOG_NAME = 'DEV' AND STAGE_TYPE = 'INTERNAL'
UNION ALL
SELECT 
    'File Formats' as OBJECT_TYPE,
    COUNT(*) as COUNT
FROM DEV.INFORMATION_SCHEMA.FILE_FORMATS
WHERE CATALOG_NAME = 'DEV'
UNION ALL
SELECT 
    'Tables' as OBJECT_TYPE,
    COUNT(*) as COUNT
FROM DEV.INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG = 'DEV' AND TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 
    'Procedures' as OBJECT_TYPE,
    COUNT(*) as COUNT
FROM DEV.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_CATALOG = 'DEV';