-- =====================================================
-- OTHER_SOURCES SCHEMA SETUP
-- =====================================================

USE DATABASE DEV;

-- Create schema
CREATE SCHEMA IF NOT EXISTS OTHER_SOURCES
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Schema for miscellaneous data sources';

USE SCHEMA OTHER_SOURCES;

-- Create internal stage
CREATE OR REPLACE STAGE OTHER_SOURCES_STAGE
    COMMENT = 'Internal stage for loading other source data'
    DIRECTORY = (ENABLE = TRUE);

-- Create CSV file format
CREATE OR REPLACE FILE FORMAT OTHER_SOURCES_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = 'AUTO'
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- Create JSON file format
CREATE OR REPLACE FILE FORMAT OTHER_SOURCES_JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    STRIP_OUTER_ARRAY = TRUE
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO';

-- Create Parquet file format
CREATE OR REPLACE FILE FORMAT OTHER_SOURCES_PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'AUTO'
    BINARY_AS_TEXT = FALSE;

-- Verify creation
SHOW STAGES IN SCHEMA OTHER_SOURCES;
SHOW FILE FORMATS IN SCHEMA OTHER_SOURCES;