-- =====================================================
-- ROLES AND PERMISSIONS SETUP
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- Create developer role
CREATE ROLE IF NOT EXISTS DEV_DEVELOPER
    COMMENT = 'Developer role for DEV database';

-- Create analyst role
CREATE ROLE IF NOT EXISTS DEV_ANALYST
    COMMENT = 'Analyst role for read-only access';

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_DEVELOPER;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEV_ANALYST;

-- Grant database access
GRANT USAGE ON DATABASE DEV TO ROLE DEV_DEVELOPER;
GRANT USAGE ON DATABASE DEV TO ROLE DEV_ANALYST;

-- Grant schema permissions to developer
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DEV TO ROLE DEV_DEVELOPER;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE DEV TO ROLE DEV_DEVELOPER;
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE DEV TO ROLE DEV_DEVELOPER;
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE DEV TO ROLE DEV_DEVELOPER;

-- Grant read permissions to analyst
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEV TO ROLE DEV_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE DEV TO ROLE DEV_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE DEV TO ROLE DEV_ANALYST;

-- Grant stage operations
GRANT READ, WRITE ON ALL STAGES IN DATABASE DEV TO ROLE DEV_DEVELOPER;
GRANT READ ON ALL STAGES IN DATABASE DEV TO ROLE DEV_ANALYST;